### ISSUE TITLE
Incorrect sort order

### ISSUE THREAD

**Issue by thewarlok666** [wishhhmaster/CoinTNet#4]
Using a 2 digit date format (##/##/####) should fix this.

![0 0 0 4 incorrect sort order](https://cloud.githubusercontent.com/assets/6732394/2986921/ede2e83c-dc48-11e3-9982-867167094816.png)

**Comment by wishhhmaster** [comment]
Cryptsy does not sort the orders by date automatically, unlike Bitstamp/BTC-e. I'll sort the orders in code. However, to display dates like ##/##/####, I need to now whether the user prefers to use dd/mm/YYYY or mm/dd/YYYY. Maybe I could just display them like YYYY-mm-dd? Otherwise, I could ask the user to select his date format in the options form.

**Comment by thewarlok666** [comment]
You know the APIs better than I do. I do think making it select-able within the options screen would be preferable due to an individuals locale. Also, I think such a change should be displayed everywhere time/date info is displayed for consistency. This is kind of a minor issue but it does exist.

Peace

**Comment by wishhhmaster** [comment]
Yes, true. Also, on a related note, time for candles is UTC time. I'll probably need to add an option to display the data in the user's local time

**Comment by thewarlok666** [comment]
This may help. No point in recreating the wheel...

https://www.google.com/#q=convert+utc+to+local+time+c%23

Peace

**Comment by wishhhmaster** [comment]
dcdd9da6e41277589af08997da7b21192cc409e3: I changed the display to YYYY-MM-dd HH:mm:ss, and the default sorting order is now by descending date

**Comment by wishhhmaster** [comment]
I'll add support for local times at a later stage
